on: 
  push:
    branches:
      - master

name: Push to Master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MATT_AZ_SECRET}}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
             az vm run-command invoke --command-id RunPowershellScript --name RockProd -g rg-rock-cus --scripts 'cd C:\\inetpub\\wwwroot\\Themes\\CCC_Public; git fetch; git checkout -f master;  git pull -f'
