on: 
  push:
    branches:
      - stage

name: Push to Stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MATT_AZ_SECRET_STAGE}}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
             az vm run-command invoke --command-id RunPowershellScript --name ROCKSTAGE -g rg-rock-stage-cus --scripts 'cd C:\\inetpub\\wwwroot\\Themes\\CCC_Public; git fetch; git checkout -f stage;  git pull -f'
